-- AlterTable
ALTER TABLE `Order` ADD COLUMN `firstTouchSource` VARCHAR(191) NULL,
    ADD COLUMN `firstTouchMedium` VARCHAR(191) NULL,
    ADD COLUMN `firstTouchCampaign` VARCHAR(191) NULL,
    ADD COLUMN `firstTouchContent` VARCHAR(191) NULL,
    ADD COLUMN `firstTouchTerm` VARCHAR(191) NULL,
    ADD COLUMN `firstTouchGclid` VARCHAR(191) NULL,
    ADD COLUMN `firstTouchFbclid` VARCHAR(191) NULL,
    ADD COLUMN `firstTouchReferrer` TEXT NULL,
    ADD COLUMN `firstTouchLandingPage` TEXT NULL,
    ADD COLUMN `lastTouchSource` VARCHAR(191) NULL,
    ADD COLUMN `lastTouchMedium` VARCHAR(191) NULL,
    ADD COLUMN `lastTouchCampaign` VARCHAR(191) NULL,
    ADD COLUMN `lastTouchContent` VARCHAR(191) NULL,
    ADD COLUMN `lastTouchTerm` VARCHAR(191) NULL,
    ADD COLUMN `lastTouchGclid` VARCHAR(191) NULL,
    ADD COLUMN `lastTouchFbclid` VARCHAR(191) NULL,
    ADD COLUMN `lastTouchReferrer` TEXT NULL,
    ADD COLUMN `lastTouchLandingPage` TEXT NULL,
    ADD COLUMN `checkoutPage` TEXT NULL,
    ADD COLUMN `trackingUserAgent` TEXT NULL,
    ADD COLUMN `trackingDevice` VARCHAR(191) NULL;
