ALTER TABLE `AbandonedCheckout`
  ADD COLUMN IF NOT EXISTS `checkoutUrl` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `messageStep` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `lastMessageAt` DATETIME(0) NULL,
  ADD COLUMN IF NOT EXISTS `repliedAt` DATETIME(0) NULL,
  ADD COLUMN IF NOT EXISTS `updatedAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS `AbandonedCheckout_lastMessageAt_idx` ON `AbandonedCheckout`(`lastMessageAt`);
