type Lang = 'pt' | 'en' | 'es' | 'it' | 'fr'

type TranslateOptions = {
  lang: Lang
}

function applyReplacements(input: string, pairs: Array<[RegExp, string]>): string {
  return pairs.reduce((acc, [re, to]) => acc.replace(re, to), input)
}

const commonToEn: Array<[RegExp, string]> = [
  [/\bLicenças Digitais\b/gi, 'Digital Licenses'],
  [/\blicenças digitais\b/gi, 'digital licenses'],
  [/\bLicença\b/gi, 'License'],
  [/\blicença\b/gi, 'license'],
  [/\bimediato\b/gi, 'immediate'],
  [/\bImediato\b/gi, 'Immediate'],
  [/\bapós\b/gi, 'after'],
  [/\bApós\b/gi, 'After'],
  [/\bconfirmação\b/gi, 'confirmation'],
  [/\bConfirmação\b/gi, 'Confirmation'],
  [/\bhorário comercial\b/gi, 'business hours'],
  [/\bChave\b/gi, 'Key'],
  [/\bchave\b/gi, 'key'],
  [/\bAtivação\b/gi, 'Activation'],
  [/\bativação\b/gi, 'activation'],
  [/\bTutorial\b/gi, 'Tutorial'],
  [/\bEntrega digital\b/gi, 'Digital delivery'],
  [/\bEntrega\b/gi, 'Delivery'],
  [/\bentrega\b/gi, 'delivery'],
  [/\bEnvio\b/gi, 'Delivery'],
  [/\benvio\b/gi, 'delivery'],
  [/\bEnvio por e-mail\b/gi, 'Email delivery'],
  [/\be-mail\b/gi, 'email'],
  [/\bpor e-mail\b/gi, 'by email'],
  [/\bSuporte\b/gi, 'Support'],
  [/\bsuporte\b/gi, 'support'],
  [/\bPagamento\b/gi, 'Payment'],
  [/\bpagamento\b/gi, 'payment'],
  [/\bconfirmação\b/gi, 'confirmation'],
  [/\bConfirmação\b/gi, 'Confirmation'],
  [/\bWindows Server\b/gi, 'Windows Server'],
  [/\bMicrosoft 365\b/gi, 'Microsoft 365'],
  [/\bOffice 365\b/gi, 'Office 365'],
  [/\bOffice\b/gi, 'Office'],
  [/\bWindows\b/gi, 'Windows'],
  [/\bProduto\b/gi, 'Product'],
  [/\bproduto\b/gi, 'product'],
  [/\bComprar agora\b/gi, 'Buy now'],
  [/\bVer tutorial\b/gi, 'View tutorial'],
  [/\bTutorial de Ativação\b/gi, 'Activation tutorial'],
  [/\bSem conteúdo\b/gi, 'No content.'],
  [/\bCarregando\b/gi, 'Loading'],
  [/\bnão encontrado\b/gi, 'not found']
]

const commonToEs: Array<[RegExp, string]> = [
  [/\bLicenças Digitais\b/gi, 'Licencias digitales'],
  [/\blicenças digitais\b/gi, 'licencias digitales'],
  [/\bLicença\b/gi, 'Licencia'],
  [/\blicença\b/gi, 'licencia'],
  [/\bimediato\b/gi, 'inmediato'],
  [/\bImediato\b/gi, 'Inmediato'],
  [/\bapós\b/gi, 'después'],
  [/\bApós\b/gi, 'Después'],
  [/\bconfirmação\b/gi, 'confirmación'],
  [/\bConfirmação\b/gi, 'Confirmación'],
  [/\bhorário comercial\b/gi, 'horario comercial'],
  [/\bChave\b/gi, 'Clave'],
  [/\bchave\b/gi, 'clave'],
  [/\bAtivação\b/gi, 'Activación'],
  [/\bativação\b/gi, 'activación'],
  [/\bTutorial\b/gi, 'Tutorial'],
  [/\bEntrega digital\b/gi, 'Entrega digital'],
  [/\bEntrega\b/gi, 'Entrega'],
  [/\bentrega\b/gi, 'entrega'],
  [/\bEnvio\b/gi, 'Envío'],
  [/\benvio\b/gi, 'envío'],
  [/\bEnvio por e-mail\b/gi, 'Envío por e-mail'],
  [/\be-mail\b/gi, 'e-mail'],
  [/\bpor e-mail\b/gi, 'por e-mail'],
  [/\bSuporte\b/gi, 'Soporte'],
  [/\bsuporte\b/gi, 'soporte'],
  [/\bPagamento\b/gi, 'Pago'],
  [/\bpagamento\b/gi, 'pago'],
  [/\bconfirmação\b/gi, 'confirmación'],
  [/\bConfirmação\b/gi, 'Confirmación'],
  [/\bWindows Server\b/gi, 'Windows Server'],
  [/\bMicrosoft 365\b/gi, 'Microsoft 365'],
  [/\bOffice 365\b/gi, 'Office 365'],
  [/\bOffice\b/gi, 'Office'],
  [/\bWindows\b/gi, 'Windows'],
  [/\bProduto\b/gi, 'Producto'],
  [/\bproduto\b/gi, 'producto'],
  [/\bComprar agora\b/gi, 'Comprar ahora'],
  [/\bVer tutorial\b/gi, 'Ver tutorial'],
  [/\bTutorial de Ativação\b/gi, 'Tutorial de activación'],
  [/\bSem conteúdo\b/gi, 'Sin contenido.'],
  [/\bCarregando\b/gi, 'Cargando'],
  [/\bnão encontrado\b/gi, 'no encontrado']
]

const commonToIt: Array<[RegExp, string]> = [
  [/\bLicenças Digitais\b/gi, 'Licenze digitali'],
  [/\blicenças digitais\b/gi, 'licenze digitali'],
  [/\bLicença\b/gi, 'Licenza'],
  [/\blicença\b/gi, 'licenza'],
  [/\bimediato\b/gi, 'immediato'],
  [/\bImediato\b/gi, 'Immediato'],
  [/\bapós\b/gi, 'dopo'],
  [/\bApós\b/gi, 'Dopo'],
  [/\bconfirmação\b/gi, 'conferma'],
  [/\bConfirmação\b/gi, 'Conferma'],
  [/\bhorário comercial\b/gi, 'orari di ufficio'],
  [/\bChave\b/gi, 'Chiave'],
  [/\bchave\b/gi, 'chiave'],
  [/\bAtivação\b/gi, 'Attivazione'],
  [/\bativação\b/gi, 'attivazione'],
  [/\bEntrega digital\b/gi, 'Consegna digitale'],
  [/\bEntrega\b/gi, 'Consegna'],
  [/\bentrega\b/gi, 'consegna'],
  [/\bEnvio\b/gi, 'Consegna'],
  [/\benvio\b/gi, 'consegna'],
  [/\bSuporte\b/gi, 'Supporto'],
  [/\bsuporte\b/gi, 'supporto'],
  [/\bPagamento\b/gi, 'Pagamento'],
  [/\bpagamento\b/gi, 'pagamento'],
  [/\bconfirmação\b/gi, 'conferma'],
  [/\bConfirmação\b/gi, 'Conferma'],
  [/\bProduto\b/gi, 'Prodotto'],
  [/\bproduto\b/gi, 'prodotto'],
  [/\bComprar agora\b/gi, 'Acquista ora'],
  [/\bVer tutorial\b/gi, 'Vedi tutorial'],
  [/\bSem conteúdo\b/gi, 'Nessun contenuto.'],
  [/\bCarregando\b/gi, 'Caricamento'],
  [/\bnão encontrado\b/gi, 'non trovato']
]

const commonToFr: Array<[RegExp, string]> = [
  [/\bLicenças Digitais\b/gi, 'Licences numériques'],
  [/\blicenças digitais\b/gi, 'licences numériques'],
  [/\bLicença\b/gi, 'Licence'],
  [/\blicença\b/gi, 'licence'],
  [/\bimediato\b/gi, 'immédiat'],
  [/\bImediato\b/gi, 'Immédiat'],
  [/\bapós\b/gi, 'après'],
  [/\bApós\b/gi, 'Après'],
  [/\bconfirmação\b/gi, 'confirmation'],
  [/\bConfirmação\b/gi, 'Confirmation'],
  [/\bhorário comercial\b/gi, "heures ouvrées"],
  [/\bChave\b/gi, 'Clé'],
  [/\bchave\b/gi, 'clé'],
  [/\bAtivação\b/gi, 'Activation'],
  [/\bativação\b/gi, 'activation'],
  [/\bEntrega digital\b/gi, 'Livraison numérique'],
  [/\bEntrega\b/gi, 'Livraison'],
  [/\bentrega\b/gi, 'livraison'],
  [/\bEnvio\b/gi, 'Livraison'],
  [/\benvio\b/gi, 'livraison'],
  [/\bSuporte\b/gi, 'Support'],
  [/\bsuporte\b/gi, 'support'],
  [/\bPagamento\b/gi, 'Paiement'],
  [/\bpagamento\b/gi, 'paiement'],
  [/\bconfirmação\b/gi, 'confirmation'],
  [/\bConfirmação\b/gi, 'Confirmation'],
  [/\bProduto\b/gi, 'Produit'],
  [/\bproduto\b/gi, 'produit'],
  [/\bComprar agora\b/gi, 'Acheter maintenant'],
  [/\bVer tutorial\b/gi, 'Voir le tutoriel'],
  [/\bSem conteúdo\b/gi, 'Aucun contenu.'],
  [/\bCarregando\b/gi, 'Chargement'],
  [/\bnão encontrado\b/gi, 'introuvable']
]

const phrasesToEn: Array<[RegExp, string]> = [
  [/Após a confirmação do pagamento,/gi, 'After payment confirmation,'],
  [/após a confirmação do pagamento/gi, 'after payment confirmation'],
  [/você recebe/gi, 'you will receive'],
  [/Você recebe/gi, 'You will receive'],
  [/você utiliza/gi, 'you use'],
  [/conforme as regras do serviço/gi, 'according to the service rules'],
  [/Atualizações automáticas enquanto a assinatura estiver ativa/gi, 'Automatic updates while the subscription is active'],
  [/Tudo em um único pacote, com acesso aos recursos mais recentes da Microsoft Office\./gi, 'All in one package, with access to the latest Microsoft Office features.'],
  [/Compatibilidade e uso da/gi, 'Compatibility and use of'],
  [/Como funciona a entrega da/gi, 'How delivery works for'],
  [/Inclui:/gi, 'Includes:'],
  [/Inclui/gi, 'Includes'],
  [/Entrega:/gi, 'Delivery:'],
  [/Envio por e-mail após confirma(ç|c)ão/gi, 'Delivered by email after confirmation'],
  [/Pol(i|í)ticas:/gi, 'Policies:'],
  [/Consulte/gi, 'See'],
  [/Pol(i|í)tica de Reembolso/gi, 'Refund Policy'],
  [/Entrega digital/gi, 'Digital delivery'],
  [/Descrição Detalhada/gi, 'Detailed description'],
  [/Tenha acesso ao pacote/gi, 'Get access to the'],
  [/original com os principais aplicativos da Microsoft/gi, 'original suite with the main Microsoft apps'],
  [/para produtividade no dia a dia/gi, 'for everyday productivity'],
  [/sempre com atualizações durante o período da assinatura/gi, 'with updates throughout the subscription period'],
  [/Ideal para quem deseja comprar/gi, 'Ideal for those who want to buy'],
  [/de forma segura, prática e com suporte especializado/gi, 'securely, conveniently, with specialized support'],
  [/O que está incluso/gi, "What's included"],
  [/Ao adquirir a/gi, 'By purchasing the'],
  [/você terá acesso a/gi, 'you will have access to'],
  [/Compatibilidade e uso/gi, 'Compatibility and use'],
  [/pode ser utilizada em até/gi, 'can be used on up to'],
  [/dispositivos simultaneamente/gi, 'devices simultaneously'],
  [/Como funciona a entrega/gi, 'How delivery works'],
  [/Após a confirmação do pagamento, a entrega é 100% digital/gi, 'After payment confirmation, delivery is 100% digital'],
  [/por meio de uma conta fornecida/gi, 'through a provided account'],
  [/\(login e senha\)/gi, '(login and password)'],
  [/válida pelo período informado/gi, 'valid for the stated period'],
  [/Validade de 12 meses/gi, 'Validity: 12 months'],
  [/O acesso é feito com a conta fornecida/gi, 'Access is made with the provided account'],
  [/não é ativação em uma conta Microsoft pessoal já existente/gi, 'it is not activation on an existing personal Microsoft account'],
  [/Se tiver qualquer dúvida/gi, 'If you have any questions'],
  [/entre em contato/gi, 'contact us'],
  [/número do pedido/gi, 'order number']
]

const phrasesToEs: Array<[RegExp, string]> = [
  [/Após a confirmação do pagamento,/gi, 'Tras la confirmación del pago,'],
  [/após a confirmação do pagamento/gi, 'después de la confirmación del pago'],
  [/você recebe/gi, 'recibirás'],
  [/Você recebe/gi, 'Recibirás'],
  [/você utiliza/gi, 'utilizas'],
  [/conforme as regras do serviço/gi, 'según las reglas del servicio'],
  [/Atualizações automáticas enquanto a assinatura estiver ativa/gi, 'Actualizaciones automáticas mientras la suscripción esté activa'],
  [/Tudo em um único pacote, com acesso aos recursos mais recentes da Microsoft Office\./gi, 'Todo en un solo paquete, con acceso a las funciones más recientes de Microsoft Office.'],
  [/Compatibilidade e uso da/gi, 'Compatibilidad y uso de'],
  [/Como funciona a entrega da/gi, 'Cómo funciona la entrega de'],
  [/Inclui:/gi, 'Incluye:'],
  [/Inclui/gi, 'Incluye'],
  [/Entrega:/gi, 'Entrega:'],
  [/Pol(i|í)ticas:/gi, 'Políticas:'],
  [/Consulte/gi, 'Consulta'],
  [/Pol(i|í)tica de Reembolso/gi, 'Política de reembolso'],
  [/Entrega digital/gi, 'Entrega digital'],
  [/Descrição Detalhada/gi, 'Descripción detallada'],
  [/Tenha acesso ao pacote/gi, 'Accede al paquete'],
  [/original com os principais aplicativos da Microsoft/gi, 'original con las principales aplicaciones de Microsoft'],
  [/para produtividade no dia a dia/gi, 'para la productividad diaria'],
  [/sempre com atualizações durante o período da assinatura/gi, 'con actualizaciones durante el período de suscripción'],
  [/Ideal para quem deseja comprar/gi, 'Ideal para quien desea comprar'],
  [/de forma segura, prática e com suporte especializado/gi, 'de forma segura, práctica y con soporte especializado'],
  [/O que está incluso/gi, 'Qué incluye'],
  [/Ao adquirir a/gi, 'Al adquirir la'],
  [/você terá acesso a/gi, 'tendrás acceso a'],
  [/Compatibilidade e uso/gi, 'Compatibilidad y uso'],
  [/pode ser utilizada em até/gi, 'puede usarse en hasta'],
  [/dispositivos simultaneamente/gi, 'dispositivos simultáneamente'],
  [/Como funciona a entrega/gi, 'Cómo funciona la entrega'],
  [/Após a confirmação do pagamento, a entrega é 100% digital/gi, 'Tras la confirmación del pago, la entrega es 100% digital'],
  [/por meio de uma conta fornecida/gi, 'mediante una cuenta proporcionada'],
  [/\(login e senha\)/gi, '(usuario y contraseña)'],
  [/válida pelo período informado/gi, 'válida por el periodo informado'],
  [/Validade de 12 meses/gi, 'Validez de 12 meses'],
  [/O acesso é feito com a conta fornecida/gi, 'El acceso se realiza con la cuenta proporcionada'],
  [/não é ativação em uma conta Microsoft pessoal já existente/gi, 'no es activación en una cuenta Microsoft personal existente'],
  [/Se tiver qualquer dúvida/gi, 'Si tienes cualquier duda'],
  [/entre em contato/gi, 'ponte en contacto'],
  [/número do pedido/gi, 'número del pedido']
]

const phrasesToIt: Array<[RegExp, string]> = [
  [/Após a confirmação do pagamento,/gi, 'Dopo la conferma del pagamento,'],
  [/após a confirmação do pagamento/gi, 'dopo la conferma del pagamento'],
  [/você recebe/gi, 'riceverai'],
  [/Você recebe/gi, 'Riceverai'],
  [/você utiliza/gi, 'utilizzi'],
  [/conforme as regras do serviço/gi, 'secondo le regole del servizio'],
  [/Atualizações automáticas enquanto a assinatura estiver ativa/gi, 'Aggiornamenti automatici finché l’abbonamento è attivo'],
  [/Tudo em um único pacote, com acesso aos recursos mais recentes da Microsoft Office\./gi, 'Tutto in un unico pacchetto, con accesso alle funzionalità più recenti di Microsoft Office.'],
  [/Compatibilidade e uso da/gi, 'Compatibilità e utilizzo della'],
  [/Como funciona a entrega da/gi, 'Come funziona la consegna della'],
  [/Inclui:/gi, 'Include:'],
  [/Inclui/gi, 'Include'],
  [/Entrega:/gi, 'Consegna:'],
  [/Pol(i|í)ticas:/gi, 'Politiche:'],
  [/Consulte/gi, 'Consulta'],
  [/Pol(i|í)tica de Reembolso/gi, 'Politica di rimborso'],
  [/Entrega digital/gi, 'Consegna digitale'],
  [/Descrição Detalhada/gi, 'Descrizione dettagliata'],
  [/Produto digital\./gi, 'Prodotto digitale.'],
  [/Tenha acesso ao pacote/gi, 'Accedi al pacchetto'],
  [/original com os principais aplicativos da Microsoft/gi, 'originale con le principali applicazioni Microsoft'],
  [/para produtividade no dia a dia/gi, 'per la produttività di tutti i giorni'],
  [/sempre com atualizações durante o período da assinatura/gi, 'con aggiornamenti durante il periodo di abbonamento'],
  [/Ideal para quem deseja comprar/gi, 'Ideale per chi desidera acquistare'],
  [/de forma segura, prática e com suporte especializado/gi, 'in modo sicuro e pratico, con supporto specializzato'],
  [/O que está incluso/gi, 'Cosa è incluso'],
  [/Ao adquirir a/gi, 'Acquistando la'],
  [/você terá acesso a/gi, 'avrai accesso a'],
  [/Compatibilidade e uso/gi, 'Compatibilità e utilizzo'],
  [/pode ser utilizada em até/gi, 'può essere utilizzata su fino a'],
  [/dispositivos simultaneamente/gi, 'dispositivi contemporaneamente'],
  [/Como funciona a entrega/gi, 'Come funziona la consegna'],
  [/Após a confirmação do pagamento, a entrega é 100% digital/gi, 'Dopo la conferma del pagamento, la consegna è 100% digitale'],
  [/por e-mail/gi, 'via email'],
  [/após/gi, 'dopo'],
  [/por meio de uma conta fornecida/gi, 'tramite un account fornito'],
  [/\(login e senha\)/gi, '(login e password)'],
  [/válida pelo período informado/gi, 'valida per il periodo indicato'],
  [/Validade de 12 meses/gi, 'Validità: 12 mesi'],
  [/O acesso é feito com a conta fornecida/gi, "L'accesso avviene con l'account fornito"],
  [/não é ativação em uma conta Microsoft pessoal já existente/gi, 'non è un’attivazione su un account Microsoft personale già esistente'],
  [/Se tiver qualquer dúvida/gi, 'Se hai domande'],
  [/entre em contato/gi, 'contattaci'],
  [/número do pedido/gi, "numero dell'ordine"]
]

const phrasesToFr: Array<[RegExp, string]> = [
  [/Após a confirmação do pagamento,/gi, 'Après confirmation du paiement,'],
  [/após a confirmação do pagamento/gi, 'après confirmation du paiement'],
  [/você recebe/gi, 'vous recevrez'],
  [/Você recebe/gi, 'Vous recevrez'],
  [/você utiliza/gi, 'vous utilisez'],
  [/conforme as regras do serviço/gi, 'selon les règles du service'],
  [/Atualizações automáticas enquanto a assinatura estiver ativa/gi, "Mises à jour automatiques tant que l’abonnement est actif"],
  [/Tudo em um único pacote, com acesso aos recursos mais recentes da Microsoft Office\./gi, "Tout dans un seul pack, avec accès aux fonctionnalités les plus récentes de Microsoft Office."],
  [/Compatibilidade e uso da/gi, "Compatibilité et utilisation de"],
  [/Como funciona a entrega da/gi, "Comment fonctionne la livraison de"],
  [/Inclui:/gi, 'Inclus :'],
  [/Inclui/gi, 'Inclus'],
  [/Entrega:/gi, 'Livraison :'],
  [/Pol(i|í)ticas:/gi, 'Politiques :'],
  [/Consulte/gi, 'Consultez'],
  [/Pol(i|í)tica de Reembolso/gi, 'Politique de remboursement'],
  [/Entrega digital/gi, 'Livraison numérique'],
  [/Descrição Detalhada/gi, 'Description détaillée'],
  [/Tenha acesso ao pacote/gi, 'Accédez au pack'],
  [/original com os principais aplicativos da Microsoft/gi, 'original avec les principales applications Microsoft'],
  [/para produtividade no dia a dia/gi, 'pour la productivité au quotidien'],
  [/sempre com atualizações durante o período da assinatura/gi, "avec des mises à jour pendant la période d'abonnement"],
  [/Ideal para quem deseja comprar/gi, 'Idéal pour ceux qui souhaitent acheter'],
  [/de forma segura, prática e com suporte especializado/gi, 'de manière sûre et pratique, avec un support spécialisé'],
  [/O que está incluso/gi, 'Ce qui est inclus'],
  [/Ao adquirir a/gi, "En achetant la"],
  [/você terá acesso a/gi, 'vous aurez accès à'],
  [/Compatibilidade e uso/gi, 'Compatibilité et utilisation'],
  [/pode ser utilizada em até/gi, "peut être utilisée sur jusqu'à"],
  [/dispositivos simultaneamente/gi, 'appareils simultanément'],
  [/Como funciona a entrega/gi, 'Comment fonctionne la livraison'],
  [/Após a confirmação do pagamento, a entrega é 100% digital/gi, 'Après confirmation du paiement, la livraison est 100% numérique'],
  [/por meio de uma conta fornecida/gi, 'via un compte fourni'],
  [/\(login e senha\)/gi, '(identifiant et mot de passe)'],
  [/válida pelo período informado/gi, 'valide pour la période indiquée'],
  [/Validade de 12 meses/gi, 'Validité : 12 mois'],
  [/O acesso é feito com a conta fornecida/gi, "L'accès se fait avec le compte fourni"],
  [/não é ativação em uma conta Microsoft pessoal já existente/gi, "ce n'est pas une activation sur un compte Microsoft personnel existant"],
  [/Se tiver qualquer dúvida/gi, 'Si vous avez des questions'],
  [/entre em contato/gi, 'contactez-nous'],
  [/número do pedido/gi, 'numéro de commande']
]

export function autoTranslateText(text: string | null | undefined, opts: TranslateOptions): string | null {
  if (text === null || text === undefined) return null
  const raw = String(text)
  const lang = opts.lang
  if (lang === 'pt') return raw

  const common =
    lang === 'en'
      ? commonToEn
      : lang === 'es'
        ? commonToEs
        : lang === 'it'
          ? commonToIt
          : commonToFr
  const phrases =
    lang === 'en'
      ? phrasesToEn
      : lang === 'es'
        ? phrasesToEs
        : lang === 'it'
          ? phrasesToIt
          : phrasesToFr

  const step1 = applyReplacements(raw, phrases)
  const step2 = applyReplacements(step1, common)
  return step2
}

export function autoTranslateMaybe(input: unknown, opts: TranslateOptions): unknown {
  if (typeof input !== 'string') return input
  return autoTranslateText(input, opts)
}
